routes/web.php
<?php

use App\Http\Controllers\Blog\PostsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontController@index');
Route::get('/blog/post/{post}', [PostsController::class, 'show'])->name('blog.show');
Route::get('/blog/category/{category}', [PostsController::class, 'category'])->name('blog.list');

// this route for pivot table for getting the posts list by tags
Route::get('/blog/tags/{tag}', [PostsController::class, 'tag'])->name('blog.tag');

// Route::get('/blog/writer/{post}', [PostsController::class, 'writer'])->name('blog.writer');

Route::get('/blog/contributor/{post}', [PostsController::class, 'writer'])->name('blog.writer');

Route::get('/paper/{post}', [PostsController::class, 'paper'])->name('paper');

Route::get('/paper/uploads/{paper}', [PostsController::class, 'uploads'])->name('paper.uploads');

Route::get('/paper/uploads/category/{category}', [PostsController::class, 'paperByCid'])->name('paper.category');

Auth::routes();

Route::middleware(['auth'])->group(function(){

	Route::get('/home', 'HomeController@index')->name('home');
	
	Route::resource('categories', 'CategoriesController');
	Route::resource('tags', 'TagsController');
	Route::resource('posts', 'PostsController');
	
	Route::get('trashed-posts', 'PostsController@trashed')->name('trashed-posts.index');
	Route::put('restore-post/{post}', 'PostsController@restore')->name('restore-posts');

	Route::get('users/profile', 'UsersController@edit')->name('users.edit-profile');
	Route::put('users/profile', 'UsersController@update')->name('users.update-profile');

    Route::get('/papers',  'PapersController@index')->name('papers.index');
	Route::get('/papers/upload', 'PapersController@create')->name('papers.upload');
	Route::post('/papers/store',  'PapersController@store')->name('papers.store');
	Route::get('papers/{paper}/edit', 'PapersController@edit')->name('papers.edit');
	Route::delete('papers/{paper}',  'PapersController@destroy');

	Route::post('profile/{profileId}/follow', 'ProfileController@followUser')->name('user.follow');
    Route::post('/{profileId}/unfollow', 'ProfileController@unFollowUser')->name('user.unfollow');

    Route::post('/like', [PostsController::class, 'likePost'])->name('like');

    Route::post('/comment/{post}', 'CommentController@store')->name('comment.store');
    Route::post('/comment-reply/{comment}', 'CommentReplyController@store')->name('reply.store');

    Route::get('/comments', 'CommentController@index')->name('comment.index');
    Route::delete('/comment/{id}', 'CommentController@destroy')->name('comment.destroy');
    Route::get('/reply-comments', 'CommentReplyController@index')->name('reply-comment.index');
    Route::delete('/reply-comment/{id}', 'CommentReplyController@destroy')->name('reply-comment.destroy');

    // Route::get('/post-liked-users/{post}', 'PostsController@likedUsers')->name('post.like.users');

});


Route::middleware(['auth', 'admin'])->group(function(){
	// Route::get('users/profile', 'UsersController@edit')->name('users.edit-profile');
	// Route::put('users/profile', 'UsersController@update')->name('users.update-profile');
	Route::get('users', 'UsersController@index')->name('users.index');
	Route::post('users/{user}/make-admin', 'UsersController@makeAdmin')->name('users.make-admin');

    Route::get('admin/dashboard', 'Admin\AdminController@dashboard')->name('admin.home');

    Route::get('admin/users', 'Admin\AdminController@users')->name('admin.users');

    Route::get('admin/posts', 'Admin\AdminController@posts')->name('admin.posts');

    Route::get('admin/categories', 'Admin\AdminController@categories')->name('admin.categories');

    Route::get('admin/tags', 'Admin\AdminController@tags')->name('admin.tags');

    Route::get('admin/pages', 'PagesController@index')->name('admin.pages');

    Route::get('admin/page/create', 'PagesController@create')->name('admin.page.create');

    Route::resource('pages', 'PagesController');


    Route::get('admin/news', 'NewsController@index')->name('admin.news');

    Route::get('admin/news/create', 'NewsController@create')->name('admin.create');

    Route::resource('news', 'NewsController');

    Route::get('featuredCategories', 'Admin\AdminController@featuredCategories');
    Route::get('statusCategories', 'Admin\AdminController@statusCategories');
    Route::get('statusUsers', 'Admin\AdminController@statusUsers');
    Route::get('statusPost', 'Admin\AdminController@statusPost');
    Route::get('statusTag', 'Admin\AdminController@statusTag');
    Route::get('statusPage', 'Admin\AdminController@statusPage');
    Route::get('statusNews', 'Admin\AdminController@statusNews');

	
});


Route::get('/admin-control', 'Admin\AdminController@login')->name('adminControl');
Route::post('/login', 'Admin\AuthController@login')->name('admin.login');
Route::get('/logout', 'Admin\AuthController@logout')->name('admin.logout');	

Route::get('/news/{news}', 'NewsController@show')->name('news.show');
Route::get('/news', 'NewsController@index')->name('news');

Route::get('/page/{page}', 'PagesController@show')->name('pages.show');

Route::any('search','FrontController@result')->name('search');

// Route::get('/page', 'FrontController@index1')->name('pages');

// Route::middleware(['auth', 'user'])->group(function(){
// 	Route::get('users/profile', 'UsersController@edit')->name('users.edit-profile');
// 	Route::put('users/profile', 'UsersController@update')->name('users.update-profile');
// 	Route::get('users', 'UsersController@index')->name('users.index');
// 	Route::post('users/{user}/make-admin', 'UsersController@makeAdmin')->name('users.make-admin');
// });

//Route::get('/admin-control', [AdminController::class, 'show'])->name('admin.show');
// Route::get('/admin-control', [AdminController::class, 'index'])->name('admin.index');

// Route::get('/papers',  'PapersController@index')->name('papers.index');
// Route::get('/papers/upload', 'PapersController@create')->name('papers.upload');
// Route::post('/papers/store',  'PapersController@store')->name('papers.store');
// Route::get('papers/{paper}/edit', 'PapersController@edit')->name('papers.edit');
// Route::delete('papers/{paper}',  'PapersController@destroy');

 // Route::post('profile/{profileId}/follow', 'ProfileController@followUser')->name('user.follow');
 // Route::post('/{profileId}/unfollow', 'ProfileController@unFollowUser')->name('user.unfollow');

Route::post('/ajax-image-upload','Admin\AdminController@Imagestore')->name('Imagestore');

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


class Tag extends Model
{
    protected $fillable = ['name', 'user_id'];

    public function posts()
    {
    	return $this->belongsToMany(Post::class);
    }
}

app/Http/Controllers/TagsController.php
<?php

namespace App\Http\Controllers;

use App\Tag;
use App\Page;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\Tags\CreateTagRequest;
use App\Http\Requests\Tags\UpdateTagsRequest;

class TagsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {    
        $user =  Auth::user();
        return view('tags.index')
        ->with('tags', Tag::where('user_id', $user->id)->get())
        ->with('pages', Page::orderBy('ordering', 'asc')->get());
    }
    
    // $user =  Auth::user();
    //   $posts = Post::where('user_id', $user->id)->get();

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tags.create')
        ->with('pages', Page::orderBy('ordering', 'asc')->get());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateTagRequest $request)
    {
        
        Tag::create([
            'name' => $request->name,
            'user_id' => auth()->user()->id
        ]);
        session()->flash('success', 'Tag created successfully.'); 
        return redirect(route('tags.index'));
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $Tag)
    {
        return view('tags.create')
        ->with('tag', $Tag)
        ->with('pages', Page::orderBy('ordering', 'asc')->get());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateTagsRequest $request, Tag $tag)
    {
        $tag->update([
           'name' => $request->name,
           'user_id' => auth()->user()->id
        ]);

        $tag->save();
        session()->flash('success', 'Tag updated successfully.');
        return redirect(route('tags.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag)
    {
        if($tag->posts->count() > 0) {
               session()->flash('error', 'Tag cannot be deleted because it is associated to some posts.');
               return redirect()->back();
        }
        $tag->delete();
        session()->flash('success', 'Tag deleted successfully.');
        return redirect(route('tags.index'));
    }
}

resources/views/tags/create.blade.php
@extends('layouts.app')

@section('title')
  Scholar Nepal | Create tag
@endsection

@section('content')

<div class="card card-default">
  <div class="card-header">
    {{ isset($tag) ? 'Edit tag' : 'Create tag' }}
  </div>

  <div class="card-body">
    
    @include('partials.errors')
  
    <form action="{{ isset($tag) ? route('tags.update', $tag->id) : route('tags.store') }}" method="POST">   
      @csrf

	     @if(isset($tag))
	       @method('PUT')
	     @endif

      <div class="form-group">
        <label for="name">Name</label>
        <input type="text" name="name" id="name" class="form-control" value="{{ isset($tag) ? $tag->name : ''}}">
      </div>

      <div class="form-group">
         <button class="btn btn-success">
           {{ isset($tag) ? 'Update tag' : 'Add tag' }}
         </button>
      </div>

    </form>
  </div> 

</div>

@endsection

resources/views/tags/index.blade.php
@extends('layouts.app')

@section('title')
  Scholar Nepal | Create Tags
@endsection

@section('content')

<div class="d-flex justify-content-end mb-2">
 <a href="{{ route('tags.create') }}" class="btn btn-success">Add tag</a>
</div>

<div class="card card-default">
  <div class="card-header">
     tags <span class="badge bg-warning">{{ $tags->count() }}</span> 
  </div>

  <div class="card-body">
   @if($tags->count() > 0)
     <table class="table">
      <thead> 
        <th>Name</th>
        <th>Posts Count</th>
        <th>Action</th>
      </thead>
      <tbody>
      @foreach($tags as $tag)
        <tr>
          <td>{{ $tag->name }}</td>
          <td>{{ $tag->posts->count() }} </td>
          <td>
          	<a href="{{ route('tags.edit', $tag->id) }}" class="btn btn-info btn-info">Edit</a>
            <button class="btn btn-info btn-danger" onclick="handleDelete({{ $tag->id }})">Delete</button>
          </td>
        </tr>
      @endforeach
      </tbody>   	
     </table> 
    @else
     <h6 class="text-center">No tag yet</h6>
    @endif  


    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog">

        <form action="" method="POST" id="deletetag">
           @method('DELETE')
           @csrf          
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete tag</h5>
                 <button type="button" class="close" data-dismiss="modal">&times;</button>
              </div>

              <div class="modal-body">
                <p class="text-center">Are you sure you want to delete this tag?</p>
              </div>

              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">No, Go back</button>
                <button type="submit" class="btn btn-danger">Yes, Delete</button>
              </div>
            </div>
          </form>

      </div>
    </div>
  </div>
</div>

@endsection

@section('scripts')

<script type="text/javascript">
  
  function handleDelete(id) {    
    var form = document.getElementById('deletetag')
    form.action = '/tags/' + id
    console.log('deleting.', form);
    $('#deleteModal').modal('show')
  }

</script>

@endsection