routes/web.php
<?php

use App\Http\Controllers\Blog\PostsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontController@index');
Route::get('/blog/post/{post}', [PostsController::class, 'show'])->name('blog.show');
Route::get('/blog/category/{category}', [PostsController::class, 'category'])->name('blog.list');

// this route for pivot table for getting the posts list by tags
Route::get('/blog/tags/{tag}', [PostsController::class, 'tag'])->name('blog.tag');

// Route::get('/blog/writer/{post}', [PostsController::class, 'writer'])->name('blog.writer');

Route::get('/blog/contributor/{post}', [PostsController::class, 'writer'])->name('blog.writer');

Route::get('/paper/{post}', [PostsController::class, 'paper'])->name('paper');

Route::get('/paper/uploads/{paper}', [PostsController::class, 'uploads'])->name('paper.uploads');

Route::get('/paper/uploads/category/{category}', [PostsController::class, 'paperByCid'])->name('paper.category');

Auth::routes();

Route::middleware(['auth'])->group(function(){

	Route::get('/home', 'HomeController@index')->name('home');
	
	Route::resource('categories', 'CategoriesController');
	Route::resource('tags', 'TagsController');
	Route::resource('posts', 'PostsController');
	
	Route::get('trashed-posts', 'PostsController@trashed')->name('trashed-posts.index');
	Route::put('restore-post/{post}', 'PostsController@restore')->name('restore-posts');

	Route::get('users/profile', 'UsersController@edit')->name('users.edit-profile');
	Route::put('users/profile', 'UsersController@update')->name('users.update-profile');

    Route::get('/papers',  'PapersController@index')->name('papers.index');
	Route::get('/papers/upload', 'PapersController@create')->name('papers.upload');
	Route::post('/papers/store',  'PapersController@store')->name('papers.store');
	Route::get('papers/{paper}/edit', 'PapersController@edit')->name('papers.edit');
	Route::delete('papers/{paper}',  'PapersController@destroy');

	Route::post('profile/{profileId}/follow', 'ProfileController@followUser')->name('user.follow');
    Route::post('/{profileId}/unfollow', 'ProfileController@unFollowUser')->name('user.unfollow');

    Route::post('/like', [PostsController::class, 'likePost'])->name('like');

    Route::post('/comment/{post}', 'CommentController@store')->name('comment.store');
    Route::post('/comment-reply/{comment}', 'CommentReplyController@store')->name('reply.store');

    Route::get('/comments', 'CommentController@index')->name('comment.index');
    Route::delete('/comment/{id}', 'CommentController@destroy')->name('comment.destroy');
    Route::get('/reply-comments', 'CommentReplyController@index')->name('reply-comment.index');
    Route::delete('/reply-comment/{id}', 'CommentReplyController@destroy')->name('reply-comment.destroy');

    // Route::get('/post-liked-users/{post}', 'PostsController@likedUsers')->name('post.like.users');

});


Route::middleware(['auth', 'admin'])->group(function(){
	// Route::get('users/profile', 'UsersController@edit')->name('users.edit-profile');
	// Route::put('users/profile', 'UsersController@update')->name('users.update-profile');
	Route::get('users', 'UsersController@index')->name('users.index');
	Route::post('users/{user}/make-admin', 'UsersController@makeAdmin')->name('users.make-admin');

    Route::get('admin/dashboard', 'Admin\AdminController@dashboard')->name('admin.home');

    Route::get('admin/users', 'Admin\AdminController@users')->name('admin.users');

    Route::get('admin/posts', 'Admin\AdminController@posts')->name('admin.posts');

    Route::get('admin/categories', 'Admin\AdminController@categories')->name('admin.categories');

    Route::get('admin/tags', 'Admin\AdminController@tags')->name('admin.tags');

    Route::get('admin/pages', 'PagesController@index')->name('admin.pages');

    Route::get('admin/page/create', 'PagesController@create')->name('admin.page.create');

    Route::resource('pages', 'PagesController');


    Route::get('admin/news', 'NewsController@index')->name('admin.news');

    Route::get('admin/news/create', 'NewsController@create')->name('admin.create');

    Route::resource('news', 'NewsController');

    Route::get('featuredCategories', 'Admin\AdminController@featuredCategories');
    Route::get('statusCategories', 'Admin\AdminController@statusCategories');
    Route::get('statusUsers', 'Admin\AdminController@statusUsers');
    Route::get('statusPost', 'Admin\AdminController@statusPost');
    Route::get('statusTag', 'Admin\AdminController@statusTag');
    Route::get('statusPage', 'Admin\AdminController@statusPage');
    Route::get('statusNews', 'Admin\AdminController@statusNews');

	
});


Route::get('/admin-control', 'Admin\AdminController@login')->name('adminControl');
Route::post('/login', 'Admin\AuthController@login')->name('admin.login');
Route::get('/logout', 'Admin\AuthController@logout')->name('admin.logout');	

Route::get('/news/{news}', 'NewsController@show')->name('news.show');
Route::get('/news', 'NewsController@index')->name('news');

Route::get('/page/{page}', 'PagesController@show')->name('pages.show');

Route::any('search','FrontController@result')->name('search');

// Route::get('/page', 'FrontController@index1')->name('pages');

// Route::middleware(['auth', 'user'])->group(function(){
// 	Route::get('users/profile', 'UsersController@edit')->name('users.edit-profile');
// 	Route::put('users/profile', 'UsersController@update')->name('users.update-profile');
// 	Route::get('users', 'UsersController@index')->name('users.index');
// 	Route::post('users/{user}/make-admin', 'UsersController@makeAdmin')->name('users.make-admin');
// });

//Route::get('/admin-control', [AdminController::class, 'show'])->name('admin.show');
// Route::get('/admin-control', [AdminController::class, 'index'])->name('admin.index');

// Route::get('/papers',  'PapersController@index')->name('papers.index');
// Route::get('/papers/upload', 'PapersController@create')->name('papers.upload');
// Route::post('/papers/store',  'PapersController@store')->name('papers.store');
// Route::get('papers/{paper}/edit', 'PapersController@edit')->name('papers.edit');
// Route::delete('papers/{paper}',  'PapersController@destroy');

 // Route::post('profile/{profileId}/follow', 'ProfileController@followUser')->name('user.follow');
 // Route::post('/{profileId}/unfollow', 'ProfileController@unFollowUser')->name('user.unfollow');

Route::post('/ajax-image-upload','Admin\AdminController@Imagestore')->name('Imagestore');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\File; 

class Post extends Model
{
	use SoftDeletes;
	
    protected $fillable = [
      'title', 'description', 'content', 'image', 'keywords', 'published_at', 'category_id', 'user_id'
    ];

    /**
     * Delete image from the folder
     *
     * @return void
     */

    public function deleteImage()
    {
      File::delete(public_path('data/'.$this->image));
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    public function hasTag($tagId)
    {
        return in_array($tagId, $this->tags->pluck('id')->toArray());
    }

    public function user()
    {
      return $this->belongsTo(User::class);
    }

    public function likes()
    {
      return $this->hasMany(Like::class);
    }

    public function comments()
    {
        return $this->hasMany('App\Comment');
    }


}

app/Http/Controllers/Blog/PostsController.php
<?php

namespace App\Http\Controllers\Blog;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;
use App\User;
use App\Post;
use App\Tag;
use App\Category;
use App\Like;
use App\Paper;
use App\Upload;
use App\Page;
use Illuminate\Support\Facades\DB;



class PostsController extends Controller
{
    public function show(Post $post)
    {
        DB::table("posts")->where('id', $post->id)->increment('views');
    	return view('blog.show')->with('post', $post)
        ->with('pages', Page::orderBy('ordering', 'asc')->get());
    }

    public function category(Category $category)
    {
    	// $list = Post::where('category_id', $post->id)->orderBy('published_at','desc')->get();
    	// $category   = Category::where('id', $post->id)->first();
    	// return view('blog.list')->with('list', $list)->with('category', $category);

         // return view('blog.list')->with('category', $category)->with('posts', $category->posts()->simplePaginate(1)); 
        return view('blog.list')->with('category', $category)
                                ->with('posts', Post::where('category_id', $category->id)->orderBy('id', 'desc')->get())
                                ->with('pages', Page::orderBy('ordering', 'asc')->get()); 
    }

    public function writer(Post $post)
    {

    	$writerPost = Post::where('user_id', $post->id)->orderBy('published_at','desc')->get();
    	$writerProfile   = User::where('id', $post->id)->first();
        $followers  = $writerProfile->followers;
        $papers = Paper::where('user_id', $writerProfile)->get();  
    	return view('blog.writer')->with('writerPost', $writerPost)
                                  ->with('writerProfile', $writerProfile)
                                  ->with('followers', $followers)
                                  ->with('papers', $papers)
                                  ->with('pages', Page::orderBy('ordering', 'asc')->get());
    }


    public function paper(Post $post, Paper $paper)
    {

        $writerProfile   = User::where('id', $post->id)->first(); 
        $followers  = $writerProfile->followers;     
        $papers = Paper::where('user_id', $writerProfile->id)->get(); 

        return view('blog.paper')->with('papers', $papers)
                                 ->with('followers', $followers)
                                 ->with('writerProfile', $writerProfile )
                                 ->with('pages', Page::orderBy('ordering', 'asc')->get());

    }

    public function paperByCid(Category $category)
    {
      
        $papers = Paper::where('category_id', $category->id)->get(); 
        $cat   = Category::where('id', $category->id)->first(); 
        return view('blog.papercategory')
        ->with('papers', $papers)
        ->with('cat', $cat)
        ->with('pages', Page::orderBy('ordering', 'asc')->get());

    }

    public function uploads(Paper $paper)
    {
        $uploads = Upload::where('paper_id', $paper->id)->get();    
       // dd($uploads);
        return view('blog.uploads')->with('uploads', $uploads)
        ->with('paper', $paper)
        ->with('pages', Page::orderBy('ordering', 'asc')->get());
    }


    public function tag(Tag $tag) {
        return view('blog.tag')->with('tag', $tag)
                               ->with('posts', $tag->posts, Post::orderBy('id', 'desc')->get())
                               ->with('pages', Page::orderBy('ordering', 'asc')->get()); 
    }


    public function LikePost(Request $request)
    {
        $post_id = $request['postId'];
        $is_like = $request['isLike'] === 'true';
        $update = false;
        $post = Post::find($post_id);
        if (!$post) {
            return null;
        }
        $user = Auth::user();
        $like = $user->likes()->where('post_id', $post_id)->first();
        if ($like) {
            $already_like = $like->like;
            $update = true;
            if ($already_like == $is_like) {
                $like->delete();
                return null;
            }
        } else {
            $like = new Like();
        }
        $like->like = $is_like;
        $like->user_id = $user->id;
        $like->post_id = $post->id;
        if ($update) {
            $like->update();
        } else {
            $like->save();
        }
        return null;
    }


}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\Posts\CreatePostsRequest;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\Posts\UpdatePostRequest;
use App\Post;
use App\Category;
use App\Tag;
use App\Page;

class PostsController extends Controller
{

    public function __construct()
    {
        $this->middleware('VerifyCategoriesCount')->only(['create', 'store']);
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $user =  Auth::user();
       $posts = Post::where('user_id', $user->id)->get();  
       return view('posts.index', compact('user','posts'))
       ->with('pages', Page::orderBy('ordering', 'asc')->get());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       return view('posts.create')
       ->with('categories', Category::all())->with('tags', Tag::all())
       ->with('pages', Page::orderBy('ordering', 'asc')->get());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreatePostsRequest $request)
    {
       //  dd($request->all());
        // upload the image
       //  $image = $request->image->store('posts', 'uploads');

        if ($request->file('image') == null) {
            $image = 'images/no-image.png';
        }else{
           $image = $request->file('image')->store('posts', 'uploads');  
        }

        // create the post 

        $post = Post::create([
          'title' => $request->title,  
          'description' => $request->description,
          'content' => $request->content,
          'keywords' => $request->keywords,
          'image' => $image,
          'published_at' => $request->published_at,
          'category_id' => $request->category_id,
          'user_id' => auth()->user()->id         
        ]);

        if($request->tags) {
            $post->tags()->attach($request->tags);
        }

        // flash message
        session()->flash('success', 'Post created successfully.');

        // redirect
        return redirect(route('posts.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        return view('posts.create')->with('post', $post)
        ->with('categories', Category::all())->with('tags', Tag::all())
        ->with('pages', Page::orderBy('ordering', 'asc')->get());
    }

    /**
     * Update the specified resource in storage.->with('categories', Category::all())
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePostRequest $request, Post $post)
    {
        $data = $request->only(['title', 'description', 'published_at', 'content','keywords', 'category_id']);

        if($request->hasfile('image')) {
            $image = $request->file('image')->store('posts', 'uploads');
            $post->deleteImage();
            $data['image'] = $image;
        }

        if($request->tags) {
            $post->tags()->sync($request->tags);
        }

        $post->update($data);
        session()->flash('success', 'Post updated successfully.');
        return redirect(route('posts.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        
        $post = Post::withTrashed()->where('id', $id)->firstOrFail();
 
        if($post->trashed()) {
            // deleting image from the folder too
            $post->deleteImage();
            $post->forceDelete();
        } else {
            $post->delete();
        }

        session()->flash('success', 'Post deleted successfully.');
        return redirect(route('posts.index'));
    }

    /**
     * Display the list of all trashed posts.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function trashed()
    {
        $trashed = Post::onlyTrashed()->get();

        return view('posts.index')->with('posts',$trashed)
        ->with('pages', Page::orderBy('ordering', 'asc')->get());

        // return view('posts.index')->withPosts($trashed); // 
        // withPosts($trashed) Or  with('posts',$trashed); Are same but the way of writing are different

        //$post = Post::withTrashed()->where('id', $id)->firstOrFail();

    }

    public function restore($id)
    {
       $post = Post::withTrashed()->where('id', $id)->firstOrFail(); 
       $post->restore();
       session()->flash('success', 'Post restored successfully.');
       return redirect()->back();
    }

}

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('title')
  Scholar Nepal | Create Post
@endsection

@section('content')
 <div class="card card-default">
   <div class="card-header">
     {{ isset($post) ? 'Edit Post' : 'Create Post' }}  
   </div>

   <div class="card-body">

    @include('partials.errors')

    <form action="{{ isset($post) ? route('posts.update', $post->id) : route('posts.store') }}" method="POST" enctype="multipart/form-data">
      @csrf

      @if(isset($post))
         @method('PUT')
      @endif
      
     <div class="form-group">
        <label for="published_at">Published Date</label>
        <input type="text" name="published_at" id="published_at" class="form-control" value="{{ isset($post) ? $post->published_at : '' }}" required>
      </div>

      <div class="form-group">
        <label for="title">Title</label>
        <input type="text" name="title" id="title" class="form-control" value="{{ isset($post) ? $post->title : '' }}">
      </div>

      <div class="form-group">
        <label for="description">Description/Abstract</label>
        <textarea name="description" id="description" class="form-control" cols="5" rows="2">{{ isset($post) ? $post->description : '' }}</textarea>
      </div>

      <div class="form-group">
        <label for="content">Content</label>
        <!-- <textarea name="content" id="content" class="form-control" cols="5" rows="3"></textarea> -->

        <input id="content" type="hidden" name="content" value="{{ isset($post) ? $post->content : '' }}">
        <trix-editor input="content"></trix-editor>
      </div>

      
      @if(isset($post))
         <div class="form-group">
           <img src="{{ asset('data/'.$post->image) }}" alt="" width="60" />
         </div>
      @endif
     

      <div class="form-group">
        <label for="image">Image</label>
        <input type="file" name="image" id="image" class="form-control" value="">
      </div>

      <div class="form-group">
        <label for="category">Category</label>
        <select name="category_id" id="category" class="form-control cat_selector">
        <option>Select Category</option>
          @foreach($categories as $category)
            <option value="{{ $category->id }}"
              @if(isset($post))
                  @if($category->id === $post->category_id)
                    selected 
                  @endif
                @endif 
              >

              {{ $category->name }}

            </option>
          @endforeach  
        </select>
      </div>

      <div class="form-group">
           @if($tags->count() > 0)
             <label for="tags">Tags</label>
               <select name="tags[]" id="tags" class="form-control tags-selector" multiple>Tags
                 @foreach($tags as $tag)
                  <option value="{{ $tag->id }}"
                    @if(isset($post))
                      @if($post->hasTag($tag->id)) 
                        selected
                      @endif 
                    @endif   
                  >
                    {{ $tag->name }}
                  </option>
                 @endforeach 
               </select>
           @endif
      </div>

      <div class="form-group">
        <label for="keywords">Keywords</label>
        <input type="text" name="keywords" id="keywords" class="form-control" value="{{ isset($post) ? $post->keywords : '' }}">
      </div>

      <div class="form-group">
        <button type="submit" class="btn btn-success">
         {{ isset($post) ? 'Update Post' : 'Create Post' }}  
         </button>
      </div>
    	
    </form>
   </div>

 </div>

@endsection

@section('scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.js"></script>
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script type="text/javascript">
 flatpickr('#published_at', 
   @if(isset($post))
   {
    
   }
   @else
   {
    defaultDate: "today"
   }
   @endif
 )

  $(document).ready(function() {
      $('.tags-selector').select2();
      $('.cat_selector').select2();
  })

</script>
@endsection

@section('css')

 <link href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.css" rel="stylesheet">
 <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
 <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('title')
  Scholar Nepal | Posts
@endsection

@section('content')


<div class="d-flex justify-content-end mb-2">
 <a href="{{ route('posts.create') }}" class="btn btn-success">Add Post</a>
</div>

<div class="card card-default">
  <div class="card-header">
     Posts  <span class="badge bg-warning">{{ $posts->count() }}</span>  
  </div>


  <div class="card-body">
   @if($posts->count()>0)
	  <table class="table">
		    <thead> 
		      <th>Image</th>
		      <th>Title</th>
		      <th>Category</th>
		      <th>Action</th>
		    </thead>
		    <tbody>
		    @foreach($posts as $post)
		      <tr>
			      <td>
                    <img src="{{ asset('data/'.$post->image) }}" width="60" height="60" />
			      </td>
			      <td>{{ $post->title }}</td>
			      <td>
                     <a href="{{ route('categories.edit', $post->category->id) }}"> 
			        {{ $post->category->name }}
			       </a>
			      </td>
			      <!-- here category comes from model Post.php-->

                @if($post->trashed())
			      <td>
			      <form action="{{ route('restore-posts', $post->id) }}" method="POST">
				      @csrf
				      @method('PUT')
			      	<button type="submit" class="btn btn-info btn-sm">Restore</button>
			      </form>
                  </td>
                @else
                <td>
                  <a href="{{ route('posts.edit', $post->id) }}" class="btn btn-info btn-sm">Edit</a>
                  </td>
                @endif  

                  <td>
			      	<form action="{{ route('posts.destroy', $post->id) }}" method="POST">
			      		@csrf
			      		@method('DELETE')
			      		<button type="submit" class="btn btn-danger btn-sm">
			      		  {{ $post->trashed() ? 'Delete' : 'Trash'}}
			      		</button>
			      	</form>
                    
			      </td>
		      </tr>
		    @endforeach  
		    </tbody>
	   </table> 
	@else
	  <h6 class="text-center">No post yet</h6>
	@endif    
  </div>
</div>

@endsection