routes/web.php
<?php

use App\Http\Controllers\Blog\PostsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontController@index');
Route::get('/blog/post/{post}', [PostsController::class, 'show'])->name('blog.show');
Route::get('/blog/category/{category}', [PostsController::class, 'category'])->name('blog.list');

// this route for pivot table for getting the posts list by tags
Route::get('/blog/tags/{tag}', [PostsController::class, 'tag'])->name('blog.tag');

// Route::get('/blog/writer/{post}', [PostsController::class, 'writer'])->name('blog.writer');

Route::get('/blog/contributor/{post}', [PostsController::class, 'writer'])->name('blog.writer');

Route::get('/paper/{post}', [PostsController::class, 'paper'])->name('paper');

Route::get('/paper/uploads/{paper}', [PostsController::class, 'uploads'])->name('paper.uploads');

Route::get('/paper/uploads/category/{category}', [PostsController::class, 'paperByCid'])->name('paper.category');

Auth::routes();

Route::middleware(['auth'])->group(function(){

	Route::get('/home', 'HomeController@index')->name('home');
	
	Route::resource('categories', 'CategoriesController');
	Route::resource('tags', 'TagsController');
	Route::resource('posts', 'PostsController');
	
	Route::get('trashed-posts', 'PostsController@trashed')->name('trashed-posts.index');
	Route::put('restore-post/{post}', 'PostsController@restore')->name('restore-posts');

	Route::get('users/profile', 'UsersController@edit')->name('users.edit-profile');
	Route::put('users/profile', 'UsersController@update')->name('users.update-profile');

    Route::get('/papers',  'PapersController@index')->name('papers.index');
	Route::get('/papers/upload', 'PapersController@create')->name('papers.upload');
	Route::post('/papers/store',  'PapersController@store')->name('papers.store');
	Route::get('papers/{paper}/edit', 'PapersController@edit')->name('papers.edit');
	Route::delete('papers/{paper}',  'PapersController@destroy');

	Route::post('profile/{profileId}/follow', 'ProfileController@followUser')->name('user.follow');
    Route::post('/{profileId}/unfollow', 'ProfileController@unFollowUser')->name('user.unfollow');

    Route::post('/like', [PostsController::class, 'likePost'])->name('like');

    Route::post('/comment/{post}', 'CommentController@store')->name('comment.store');
    Route::post('/comment-reply/{comment}', 'CommentReplyController@store')->name('reply.store');

    Route::get('/comments', 'CommentController@index')->name('comment.index');
    Route::delete('/comment/{id}', 'CommentController@destroy')->name('comment.destroy');
    Route::get('/reply-comments', 'CommentReplyController@index')->name('reply-comment.index');
    Route::delete('/reply-comment/{id}', 'CommentReplyController@destroy')->name('reply-comment.destroy');

    // Route::get('/post-liked-users/{post}', 'PostsController@likedUsers')->name('post.like.users');

});


Route::middleware(['auth', 'admin'])->group(function(){
	// Route::get('users/profile', 'UsersController@edit')->name('users.edit-profile');
	// Route::put('users/profile', 'UsersController@update')->name('users.update-profile');
	Route::get('users', 'UsersController@index')->name('users.index');
	Route::post('users/{user}/make-admin', 'UsersController@makeAdmin')->name('users.make-admin');

    Route::get('admin/dashboard', 'Admin\AdminController@dashboard')->name('admin.home');

    Route::get('admin/users', 'Admin\AdminController@users')->name('admin.users');

    Route::get('admin/posts', 'Admin\AdminController@posts')->name('admin.posts');

    Route::get('admin/categories', 'Admin\AdminController@categories')->name('admin.categories');

    Route::get('admin/tags', 'Admin\AdminController@tags')->name('admin.tags');

    Route::get('admin/pages', 'PagesController@index')->name('admin.pages');

    Route::get('admin/page/create', 'PagesController@create')->name('admin.page.create');

    Route::resource('pages', 'PagesController');


    Route::get('admin/news', 'NewsController@index')->name('admin.news');

    Route::get('admin/news/create', 'NewsController@create')->name('admin.create');

    Route::resource('news', 'NewsController');

    Route::get('featuredCategories', 'Admin\AdminController@featuredCategories');
    Route::get('statusCategories', 'Admin\AdminController@statusCategories');
    Route::get('statusUsers', 'Admin\AdminController@statusUsers');
    Route::get('statusPost', 'Admin\AdminController@statusPost');
    Route::get('statusTag', 'Admin\AdminController@statusTag');
    Route::get('statusPage', 'Admin\AdminController@statusPage');
    Route::get('statusNews', 'Admin\AdminController@statusNews');

	
});


Route::get('/admin-control', 'Admin\AdminController@login')->name('adminControl');
Route::post('/login', 'Admin\AuthController@login')->name('admin.login');
Route::get('/logout', 'Admin\AuthController@logout')->name('admin.logout');	

Route::get('/news/{news}', 'NewsController@show')->name('news.show');
Route::get('/news', 'NewsController@index')->name('news');

Route::get('/page/{page}', 'PagesController@show')->name('pages.show');

Route::any('search','FrontController@result')->name('search');

// Route::get('/page', 'FrontController@index1')->name('pages');

// Route::middleware(['auth', 'user'])->group(function(){
// 	Route::get('users/profile', 'UsersController@edit')->name('users.edit-profile');
// 	Route::put('users/profile', 'UsersController@update')->name('users.update-profile');
// 	Route::get('users', 'UsersController@index')->name('users.index');
// 	Route::post('users/{user}/make-admin', 'UsersController@makeAdmin')->name('users.make-admin');
// });

//Route::get('/admin-control', [AdminController::class, 'show'])->name('admin.show');
// Route::get('/admin-control', [AdminController::class, 'index'])->name('admin.index');

// Route::get('/papers',  'PapersController@index')->name('papers.index');
// Route::get('/papers/upload', 'PapersController@create')->name('papers.upload');
// Route::post('/papers/store',  'PapersController@store')->name('papers.store');
// Route::get('papers/{paper}/edit', 'PapersController@edit')->name('papers.edit');
// Route::delete('papers/{paper}',  'PapersController@destroy');

 // Route::post('profile/{profileId}/follow', 'ProfileController@followUser')->name('user.follow');
 // Route::post('/{profileId}/unfollow', 'ProfileController@unFollowUser')->name('user.unfollow');

Route::post('/ajax-image-upload','Admin\AdminController@Imagestore')->name('Imagestore');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name', 'icon','user_id'];

    public function posts()
    {
    	return $this->hasMany(Post::class);
    }

   
}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Page;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\Categories\CreateCategoryRequest;
use App\Http\Requests\Categories\UpdateCategoriesRequest;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {       
        
         $user =  Auth::user();
         return view('categories.index')
         ->with('categories', Category::where('user_id', $user->id)->get())
         ->with('pages', Page::orderBy('ordering', 'asc')->get());
    }
    
  
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categories.create')
        ->with('pages', Page::orderBy('ordering', 'asc')->get());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateCategoryRequest $request)
    {    
       
        Category::create([
            'name' => $request->name,
            'icon' => $request->icon,
            'user_id' => auth()->user()->id
        ]);
        
        session()->flash('success', 'Category created successfully.'); 
        return redirect(route('categories.index'));        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('categories.create')
        ->with('category', $category)
        ->with('pages', Page::orderBy('ordering', 'asc')->get());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCategoriesRequest $request, Category $category)
    {
        $category->update([
           'name' => $request->name, 
           'icon' => $request->icon,
           'user_id' => auth()->user()->id
        ]);

        $category->save();
        session()->flash('success', 'Category updated successfully.');
        return redirect(route('categories.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        if($category->posts->count() > 0) {
            session()->flash('error', 'Category cannot be deleted because it has some posts.');
            return redirect()->back();
        }

        $category->delete();
        session()->flash('success', 'Category deleted successfully.');
        return redirect(route('categories.index'));
    }
}

resources/views/categories/create.blade.php
@extends('layouts.app')

@section('title')
  Scholar Nepal | Create Category
@endsection

@section('content')

<div class="card card-default">
  <div class="card-header">
    {{ isset($category) ? 'Edit Category' : 'Create Category' }}
  </div>

  <div class="card-body">
    
   @include('partials.errors')
  
    <form action="{{ isset($category) ? route('categories.update', $category->id) : route('categories.store') }}" method="POST">   
      @csrf

	     @if(isset($category))
	       @method('PUT')
	     @endif

      <div class="form-group">
        <label for="name">Name</label>
        <input type="text" name="name" id="name" class="form-control" value="{{ isset($category) ? $category->name : ''}}">
      </div>

      <!--<div class="form-group">-->
      <!--  <label for="Icon">Icon Code</label>-->
      <!--  <input type="text" name="icon" id="icon" class="form-control" value="{{ isset($category) ? $category->icon : ''}}">-->
      <!--</div>-->

      <div class="form-group">
         <button class="btn btn-success">
           {{ isset($category) ? 'Update Category' : 'Add Category' }}
         </button>
      </div>

    </form>
  </div> 

</div>

@endsection

resources/views/categories/index.blade.php
@extends('layouts.app')

@section('title')
  Scholar Nepal | Categories
@endsection

@section('content')

<div class="d-flex justify-content-end mb-2">
 <a href="{{ route('categories.create') }}" class="btn btn-success">Add Category</a>
</div>

<div class="card card-default">
  <div class="card-header">
     Categories <span class="badge bg-warning">{{ $categories->count() }}</span>  
  </div>

  <div class="card-body">
   @if($categories->count() > 0)
     <table class="table">
      <thead> 
        <th>Name</th>
        <!--<th>Icon</th>-->
        <th>Posts Count</th>
        <th>Action</th>
      </thead>
      <tbody>
      @foreach($categories as $category)
        <tr>
          <td>{{ $category->name }}</td>
          <!--<td>{{ $category->icon }}</td>-->
          <td>{{ $category->posts->count() }}</td>
          <td>
          	<a href="{{ route('categories.edit', $category->id) }}" class="btn btn-info btn-info">Edit</a>
            <button class="btn btn-info btn-danger" onclick="handleDelete({{ $category->id }})">Delete</button>
          </td>
        </tr>
      @endforeach
      </tbody>   	
     </table> 
    @else
     <h6 class="text-center">No category yet</h6>
    @endif  


    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog">

        <form action="" method="POST" id="deleteCategory">
           @method('DELETE')
           @csrf          
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Category</h5>
                 <button type="button" class="close" data-dismiss="modal">&times;</button>
              </div>

              <div class="modal-body">
                <p class="text-center">Are you sure you want to delete this category?</p>
              </div>

              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">No, Go back</button>
                <button type="submit" class="btn btn-danger">Yes, Delete</button>
              </div>
            </div>
          </form>

      </div>
    </div>
  </div>
</div>

@endsection

@section('scripts')

<script type="text/javascript">
  
  function handleDelete(id) {    
    var form = document.getElementById('deleteCategory')
    form.action = '/categories/' + id
    console.log('deleting.', form);
    $('#deleteModal').modal('show')
  }

</script>

@endsection